name: "Cache Rust tooling and Cargo registry"
description: "Action for caching both Rust and Cargo caches"
author: "The Dev Nolus Team <dev@nolus.io>"

runs:
  using: "composite"
  steps:
    - uses: "actions/cache@v3"
      with:
        path: |
          ~/.rustup/
          ~/.cargo/
        key: "${{ runner.os }}-cargo"
