name: "Cache Rust tooling and Cargo registry"
description: "Action for caching both Rust and Cargo caches"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  update_and_cache_toolchains:
    description: "Indicates whether to update and cache `~/.rustup/` directory."
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - uses: "actions/cache@v4"
      with:
        path: |
          ~/.cargo/
        key: "${{ runner.os }}-cargo"
    - uses: "actions/cache@v4"
      if: "fromJSON(inputs.update_and_cache_toolchains)"
      with:
        path: |
          ~/.rustup/
        key: "${{ runner.os }}-rustup"
    - if: "fromJSON(inputs.update_and_cache_toolchains)"
      shell: "sh"
      run: "rustup update"
