name: "Audit dependencies"
description: "Action for running `cargo-audit`"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  working_directory:
    description: "Sets working directory for any operations executing through `cargo`."
    required: true
  rustflags:
    description: "Value to be passed as an environment variable to the Rust build system."
    required: false

runs:
  using: "composite"
  steps:
    - shell: "sh"
      run: "cargo +stable install cargo-audit"
    - name: "Audit dependencies"
      shell: "sh"
      env:
        RUSTFLAGS: "${{ inputs.rustflags }}"
      run: "cargo audit"
      working-directory: "${{ inputs.working_directory }}"
