name: "Audit dependencies"
description: "Action for running `cargo-audit`"
author: "The Dev Nolus Team <dev@nolus.io>"

runs:
  using: "composite"
  steps:
    - shell: "sh"
      run: "cargo +stable install cargo-audit"
    - name: "Audit dependencies"
      shell: "sh"
      run: "cargo audit"
