name: "Check codebase"
description: "Action for checking codebase"
author: "The Dev Nolus Team <dev@nolus.io>"

runs:
  using: "composite"
  steps:
    - shell: "sh"
      run: "cargo +stable install cargo-hack"
    - name: "Check codebase"
      shell: "sh"
      run: "cargo hack check"
