name: "Check codebase"
description: "Action for checking codebase"
author: "The Dev Nolus Team <dev@nolus.io>"

runs:
  using: "composite"
  steps:
    - shell: "sh"
      run: "cargo install cargo-workspaces"
    - name: "Check codebase"
      shell: "sh"
      run: "cargo workspaces exec cargo check"
