name: "Check codebase"
description: "Action for checking codebase"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  working_directory:
    description: "Sets working directory for any operations executing through `cargo`."
    required: true

runs:
  using: "composite"
  steps:
    - shell: "sh"
      run: "cargo +stable install cargo-hack"
    - name: "Check codebase"
      shell: "sh"
      run: "cargo hack check"
      working-directory: "${{ inputs.working_directory }}"
