name: "Check formatting"
description: "Action for checking codebase's formatting"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  working_directory:
    description: "Sets working directory for any operations executing through `cargo`."
    required: true

runs:
  using: "composite"
  steps:
    - shell: "sh"
      run: "rustup component add rustfmt"
    - name: "Check formatting"
      shell: "sh"
      run: "cargo fmt --check"
      working-directory: "${{ inputs.working_directory }}"
