name: "Check features"
description: "Action for checking features and feature gates"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  profile:
    description: "Specifies in which profile check should be run."
    required: true
  debug_assertions:
    description: "Specifies what `debug-assertions` should be set to."

runs:
  using: "composite"
  steps:
    - shell: "sh"
      run: "cargo +stable install cargo-hack"
    - shell: "sh"
      run: |
        if ! test "${{ inputs.debug_assertions }}" = "";
          then (
            RUSTFLAGS="-C \"debug-assertions=${{ inputs.debug_assertions }}\" ${RUSTFLAGS}"
          );
        fi

        cargo hack --clean-per-run --feature-powerset clippy --profile test -- -D warnings
