name: "Check features"
description: "Action for checking features and feature gates"
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  working_directory:
    description: "Sets working directory for any operations executing through `cargo`."
    required: true
  profile:
    description: "Specifies in which profile check should be run."
    required: true
  debug_assertions:
    description: "Specifies what `debug-assertions` should be set to."
    required: false
  rustflags:
    description: "Value to be passed as an environment variable to the Rust build system."
    required: false

runs:
  using: "composite"
  steps:
    - shell: "sh"
      run: "cargo +stable install cargo-hack"
    - shell: "sh"
      env:
        RUSTFLAGS: "${{ inputs.rustflags }}"
      run: |
        if ! test "${{ inputs.debug_assertions }}" = "";
          then (
            RUSTFLAGS="-C \"debug-assertions=${{ inputs.debug_assertions }}\" ${RUSTFLAGS}"
          );
        fi

        cargo hack --clean-per-run --feature-powerset clippy --profile ${{ inputs.profile }} -- -D warnings
      working-directory: "${{ inputs.working_directory }}"
